import { useEffect, useRef } from 'react';
import { Map, NavigationControl, type GeoJSONSource } from 'maplibre-gl';
import type { FeatureCollection, Geometry } from 'geojson';
import 'maplibre-gl/dist/maplibre-gl.css';

type Data = { segments: Array<{ geometry: [number, number][]; rqi: number }>; events: Array<{ lat: number; lon: number; type: string; severity: number }>; contracts: Array<{ geometry: Geometry; roadName: string }>; replayPath?: [number, number, number][] };
const empty: FeatureCollection = { type: 'FeatureCollection', features: [] };

export default function AnalyticsMap({ data }: { data: Data | null }) {
  const el = useRef<HTMLDivElement>(null), map = useRef<Map | null>(null);
  useEffect(() => { if (!el.current) return; const m = new Map({ container: el.current, center: [79.5, 22.3], zoom: 4, style: { version: 8, sources: { osm: { type: 'raster', tiles: ['https://tile.openstreetmap.org/{z}/{x}/{y}.png'], tileSize: 256 } }, layers: [{ id: 'osm', type: 'raster', source: 'osm' }] } }); map.current = m; m.addControl(new NavigationControl(), 'top-right'); m.on('load', () => { m.addSource('segments', { type: 'geojson', data: empty }); m.addSource('events', { type: 'geojson', data: empty }); m.addSource('contracts', { type: 'geojson', data: empty }); m.addSource('replay', { type: 'geojson', data: empty }); m.addLayer({ id: 'segments', type: 'line', source: 'segments', paint: { 'line-color': ['interpolate', ['linear'], ['get', 'rqi'], 0, '#dc2626', 50, '#f59e0b', 100, '#16a34a'], 'line-width': 5 } }); m.addLayer({ id: 'contracts', type: 'line', source: 'contracts', paint: { 'line-color': '#2563eb', 'line-width': 5, 'line-dasharray': [2, 1] } }); m.addLayer({ id: 'replay', type: 'line', source: 'replay', paint: { 'line-color': '#a855f7', 'line-width': 7 } }); m.addLayer({ id: 'events', type: 'circle', source: 'events', paint: { 'circle-color': '#dc2626', 'circle-radius': ['interpolate', ['linear'], ['get', 'severity'], 0, 3, 1, 9], 'circle-stroke-color': '#fff', 'circle-stroke-width': 1 } }); }); return () => { m.remove(); map.current = null; }; }, []);
  useEffect(() => { const m = map.current; if (!m?.isStyleLoaded() || !data) return; (m.getSource('segments') as GeoJSONSource)?.setData({ type: 'FeatureCollection', features: data.segments.map((s) => ({ type: 'Feature', properties: { rqi: s.rqi }, geometry: { type: 'LineString', coordinates: s.geometry.map(([lat, lon]) => [lon, lat]) } })) }); (m.getSource('events') as GeoJSONSource)?.setData({ type: 'FeatureCollection', features: data.events.map((e) => ({ type: 'Feature', properties: e, geometry: { type: 'Point', coordinates: [e.lon, e.lat] } })) }); (m.getSource('contracts') as GeoJSONSource)?.setData({ type: 'FeatureCollection', features: data.contracts.map((c) => ({ type: 'Feature', properties: { roadName: c.roadName }, geometry: c.geometry })) }); (m.getSource('replay') as GeoJSONSource)?.setData({ type: 'FeatureCollection', features: data.replayPath?.length ? [{ type: 'Feature', properties: {}, geometry: { type: 'LineString', coordinates: data.replayPath.map(([lat, lon]) => [lon, lat]) } }] : [] }); }, [data]);
  return <div ref={el} className="mt-6 h-[30rem] overflow-hidden rounded-2xl border border-line" />;
}
