"""Parity tests for betterroads_ai.grid against backend/src/lib/roadSegments.ts.

The pinned vectors below were generated by running the exact JS implementation
(constants and expressions copied from roadSegments.ts) under Node v24:

    segmentKeyFor(lat, lon)  ->  key
    mergeRqi(prev, count, new)  ->  double (shortest round-trip repr)

Several vectors deliberately exercise IEEE-754 artifacts (12.9716 lands in
cell "12.971", not "12.972", because 12.9716/0.001 is 12971.599... in binary).
Python must reproduce these bit-for-bit, so assertions use exact equality.
"""

import math

import pytest

from betterroads_ai.grid import (
    CELL_SIZE_DEG,
    RECENCY_ALPHA_FLOOR,
    cell_center,
    clamp_rqi,
    merge_rqi,
    segment_key_for,
)

# ─── segment_key_for ─────────────────────────────────────────────────────────

JS_KEY_VECTORS = [
    (19.0596, 72.8295, "19.059:72.829"),
    (19.055, 72.84, "19.055:72.840"),
    (19.0549999, 72.8399999, "19.054:72.839"),
    (0.0004, 0.0004, "0.000:0.000"),
    (-0.0004, -0.0004, "-0.001:-0.001"),
    (-19.0596, -72.8295, "-19.060:-72.830"),
    (0.0, 0.0, "0.000:0.000"),
    (19.055000000000001, 72.84, "19.055:72.840"),
    (12.9716, 77.5946, "12.971:77.594"),  # FP artifact: floor(12971.599...)
    (28.6139, 77.2090, "28.613:77.209"),
    (19.033, 72.8397, "19.033:72.839"),
    (1e-9, -1e-9, "0.000:-0.001"),
    (89.9999, 179.9999, "89.999:179.999"),
    (-89.9999, -179.9999, "-90.000:-180.000"),
    (45.6789, -122.4567, "45.678:-122.457"),
    (19.0625, 72.0625, "19.062:72.062"),
]


@pytest.mark.parametrize("lat,lon,expected", JS_KEY_VECTORS)
def test_segment_key_matches_js(lat, lon, expected):
    assert segment_key_for(lat, lon) == expected


def test_key_always_three_decimals():
    # roadSegments.ts comment says "72.84" but toFixed(3) always emits 3
    # decimals; the schema example "19.055:72.840" is the real format.
    lat_str, lon_str = segment_key_for(7.1, 72.84).split(":")
    assert len(lat_str.split(".")[1]) == 3
    assert len(lon_str.split(".")[1]) == 3


def test_key_stable_within_cell():
    # Everything in [19.055, 19.056) x [72.840, 72.841) shares one cell.
    base = segment_key_for(19.0555, 72.8405)
    assert segment_key_for(19.0551, 72.8401) == base
    assert segment_key_for(19.0559, 72.8409) == base
    assert segment_key_for(19.0561, 72.8405) != base  # next lat cell
    assert segment_key_for(19.0555, 72.8411) != base  # next lon cell


# ─── cell_center ─────────────────────────────────────────────────────────────

JS_CENTER_VECTORS = [
    ("19.059:72.829", 19.0595, 72.8295),
    ("-19.060:-72.830", -19.0595, -72.8295),
    ("0.000:0.000", 0.0005, 0.0005),
    ("-0.001:-0.001", -0.0005, -0.0005),
]


@pytest.mark.parametrize("key,lat,lon", JS_CENTER_VECTORS)
def test_cell_center_matches_js(key, lat, lon):
    assert cell_center(key) == (lat, lon)


def test_center_lands_back_in_same_cell():
    for lat, lon, key in JS_KEY_VECTORS:
        c_lat, c_lon = cell_center(key)
        assert segment_key_for(c_lat, c_lon) == key


# ─── merge_rqi / clamp_rqi ───────────────────────────────────────────────────

JS_MERGE_VECTORS = [
    # (prev_rqi, prev_count, new_rqi, expected)
    (0, 0, 73.2, 73.2),
    (50, 0, 120, 100),  # first sample clamps high
    (50, 0, -5, 0),  # first sample clamps low
    (80, 1, 60, 70.0),  # plain mean while alpha 1/n > floor
    (80, 3, 60, 75.0),
    (80, 5, 60, 76.66666666666667),  # alpha = 1/6 (still above floor)
    (80, 6, 60, 77.0),  # alpha hits the 0.15 floor
    (80, 100, 60, 77.0),  # ... and stays there forever
    (10, 4, 99.5, 27.900000000000002),  # exact double parity with JS
    (70.123, 7, 71.987, 70.4026),
    (99, 50, 150, 100),  # merge result clamped high
    (1, 50, -50, 0),  # merge result clamped low
]


@pytest.mark.parametrize("prev,count,new,expected", JS_MERGE_VECTORS)
def test_merge_rqi_matches_js(prev, count, new, expected):
    assert merge_rqi(prev, count, new) == expected


def test_alpha_floor_value():
    # Past prev_count 6, 1/(n+1) < 0.15 so the EMA weight is constant.
    assert RECENCY_ALPHA_FLOOR == 0.15
    assert merge_rqi(80, 7, 60) == merge_rqi(80, 10_000, 60) == 77.0


def test_plain_mean_regime():
    # With few samples merge_rqi is an exact running mean: mean of [90, 70, 80].
    r = merge_rqi(90, 1, 70)
    r = merge_rqi(r, 2, 80)
    assert math.isclose(r, 80.0)


def test_clamp():
    assert clamp_rqi(-3) == 0
    assert clamp_rqi(0) == 0
    assert clamp_rqi(55.5) == 55.5
    assert clamp_rqi(100) == 100
    assert clamp_rqi(101.2) == 100


def test_constants_match_backend():
    assert CELL_SIZE_DEG == 0.001
    assert RECENCY_ALPHA_FLOOR == 0.15
